version: '3.7'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: user-crud-app
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo-data:
